### ISSUE TITLE
Cannot find 'Process' in scope

### ISSUE THREAD

**Issue by ken4ward** [kvld/allure-xcresult#3]
I recently installed this plugin to run reports on a test in XCTest, and got error as stated in the title: `Cannot find 'Process' in scope`. It seems this porject needs to e updated to use NSProcess instead of Process. 
These occurs in class: `XCResultFile` on line 135.

**Comment by kvld** [comment]
[Process](https://developer.apple.com/documentation/foundation/process) is available only for macOS. It seems that you are trying to build the library on iOS. 
`XCResultFile` is a part of XCResultKit which uses `xcresulttool` cli under the hood.
